### ISSUE TITLE
protocols 设置不生效

### ISSUE THREAD

**Issue by tuanqizhirou** [yinfujing/spring-boot-dubbo-starter-parent#1]
只能通过如下方式设置
```
dubbo:
  registries:
    - address: 10.1.1.72:2181
      protocol: zookeeper
  services:
    - interface: com.dxhy.platform.data.mongo.api.InvoiceMongoDBSaveService
      protocols:
        - name: dubbo
          port: 20442
    - interface: com.dxhy.platform.data.mongo.api.ImageCacheService
      protocols:
        - name: dubbo
          port: 20442
```
